name: flutter_landing_page
description: A responsive landing page template for flutter. Perfect for
  showcasing your product or service with a clean lead-in, FAQs, pricing, and
  key features.
publish_to: 'none'
version: 1.1.0
homepage: https://nialixus-landing-page.web.app
repository: https://github.com/Nialixus/flutter_landing_page.git
issue_tracker: https://github.com/Nialixus/flutter_landing_page/issues
funding:
  - https://www.buymeacoffee.com/nialixus
topics:
  - template
  - landing page
  - one page

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  card_swiper: ^3.0.1
  dart_fusion:
    git:
      url: https://github.com/Nialixus/dart_fusion.git
      ref: v2.9.1
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  go_router: ^12.0.1
  meta_seo: ^3.0.7
  scroll_to_id: ^1.5.1
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  package_rename: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
